using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Resources;

[assembly: ThemeInfo(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]
[assembly: AssemblyAssociatedContentFile("notosans-bold.ttf")]
[assembly: AssemblyAssociatedContentFile("notosans-bolditalic.ttf")]
[assembly: AssemblyAssociatedContentFile("notosans-italic.ttf")]
[assembly: AssemblyAssociatedContentFile("notosans-regular.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-black.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-blackitalic.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-bold.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-bolditalic.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-italic.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-light.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-lightitalic.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-medium.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-mediumitalic.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-regular.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-thin.ttf")]
[assembly: AssemblyAssociatedContentFile("roboto-thinitalic.ttf")]
[assembly: AssemblyAssociatedContentFile("robotocondensed-bold.ttf")]
[assembly: AssemblyAssociatedContentFile("robotocondensed-bolditalic.ttf")]
[assembly: AssemblyAssociatedContentFile("robotocondensed-italic.ttf")]
[assembly: AssemblyAssociatedContentFile("robotocondensed-light.ttf")]
[assembly: AssemblyAssociatedContentFile("robotocondensed-lightitalic.ttf")]
[assembly: AssemblyAssociatedContentFile("robotocondensed-regular.ttf")]
[assembly: AssemblyVersion("0.0.0.0")]
[module: RefSafetyRules(11)]
